config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py --id https://zenodo.org/records/15685917 --plugin oai-pmh --repository
          http://digital.csic.es/dspace-oai/request --api-endpoint http://localhost:9090/v1.0/rda/rda_all
          --json
        container: qc.fair_surly-flax-fousek
timeout: 5400
